## マルコフ連鎖
1個前の状態に**だけ**よって次の状態が決まる連鎖  
例) 明日の株価は1年前の株価とは関係なく、**今日の株価**だけから決まるということ

### 実装例
天気の遷移状態に関して  
参考 : https://qiita.com/yugo-yamamoto/items/1b7da9ea4a65049151da

In [1]:
import numpy as np

In [8]:
# 晴の日の翌日が、晴になる確率は 0.6 曇りになる確率は 0.3 雨になる確率は 0.1
# 曇の日の翌日が、晴になる確率は 0.3 曇りになる確率は 0.6 雨になる確率は 0.1
# 雨の日の翌日が、晴になる確率は 0.2 曇りになる確率は 0.3 雨になる確率は 0.5
# これを行列で表すと
prob_matrix = np.array([
    [0.6, 0.3, 0.1],
    [0.3, 0.6, 0.1],
    [0.2, 0.3, 0.5]
])

In [9]:
# 初期状態を晴れとして、翌日の天気の確率分布を計算(10日後まで繰り返す)
state = np.array([1, 0, 0])
for x in range(10):
    # 行列の積を求める
    state = np.dot(state, prob_matrix)
    print('{0}日後'.format(x + 1))
    print(state)

1日後
[ 0.6  0.3  0.1]
2日後
[ 0.47  0.39  0.14]
3日後
[ 0.427  0.417  0.156]
4日後
[ 0.4125  0.4251  0.1624]
5日後
[ 0.40751  0.42753  0.16496]
6日後
[ 0.405757  0.428259  0.165984]
7日後
[ 0.4051287  0.4284777  0.1663936]
8日後
[ 0.40489925  0.42854331  0.16655744]
9日後
[ 0.40481403  0.42856299  0.16662298]
10日後
[ 0.40478191  0.4285689   0.16664919]
